### ISSUE TITLE
proxy name not defined

### ISSUE THREAD

**Issue by 404-B** [hendrikbgr/YandexMail-Account-Creator#41]
Traceback (most recent call last):
  File "auto_email_list.py", line 52, in <module>
    for proxy in proxy_config.proxy:
NameError: name 'proxy_config' is not defined

**Comment by hendrikbgr** [comment]
Please completely update your version (git pull)

**Comment by 404-B** [comment]
says already up to date

**Comment by hendrikbgr** [comment]
Please check the repo. There you will see that auto_email_list.py does not longer exist. Therefore you can't have the newest version. Maybe download the project as .zip instead
