### ISSUE TITLE
error line no 172, even after adding 2captcha API key

### ISSUE THREAD

**Issue by jacoballen55** [hendrikbgr/YandexMail-Account-Creator#46]
<img width="575" alt="naL5M2o" src="https://user-images.githubusercontent.com/83693805/117112183-50667380-ada6-11eb-95e6-272635be3a59.png">

**Comment by MShawon** [comment]
`pip install -r requirements.txt`

**Comment by jacoballen55** [comment]
I did. The bot only stops on captcha. And did not enter captcha. API key is added

**Comment by MShawon** [comment]
Download the latest code then `pip install -r requirements.txt`

**Comment by jacoballen55** [comment]
It's working with new code like butter.. 
How to turn on Imap?

**Comment by hendrikbgr** [comment]
You can do it via the settings. I will add an optional script to enable after the account creation

**Comment by jacoballen55** [comment]
Can you guide me on how to add a custom chrome extension to the chrome driver? I have in both json and crx

**Comment by MShawon** [comment]
after line 128 add this line..
`options.add_extension('Your crx file name')`

and place that crx in `YandexMail-Account-Creator` directory

**Comment by hendrikbgr** [comment]
Are all issues resolved so I can close this issue?

**Comment by jacoballen55** [comment]
Yes. Thanks for the help. 
would love the IMAP enable script and adding a backup email.

**Comment by jacoballen55** [comment]
I just noticed it stops after creating 15-20 accounts and the terminal gets closed. where can I find the log to check what's wrong?

**Comment by jacoballen55** [comment]
No error. it just closes.  
Proxy count 1000

**Comment by hendrikbgr** [comment]
closed for now
