### ISSUE TITLE
iMAP

### ISSUE THREAD

**Issue by wtfismyname69420** [hendrikbgr/YandexMail-Account-Creator#47]
Is there an option to enable iMAP?

**Comment by hendrikbgr** [comment]
yes it can be enabled after the account creation. I will add an option to enable it after account creation

**Comment by ItsCEED** [comment]
> yes it can be enabled after the account creation. I will add an option to enable it after account creation

This would be an awesome addition! Hope to see it soon

**Comment by hendrikbgr** [comment]
Added with next release
