### ISSUE TITLE
Yandex blocking each account after creation 

### ISSUE THREAD

**Issue by Arinze1020** [hendrikbgr/YandexMail-Account-Creator#48]
After I finish creating the account I can't log in to it. I don't know what am doing wrong or getting wrong am using the free proxy could this be the problem?

**Comment by hendrikbgr** [comment]
What error do you get when you try and login? That the account does not exist?

**Comment by Arinze1020** [comment]
![Screenshot_20210517_093238_com brave browser](https://user-images.githubusercontent.com/33836764/118458708-ef6a6400-b6f2-11eb-9b23-79dd284864be.jpg)

All the account all returns with a restriction.

**Comment by Arinze1020** [comment]
Solved

**Comment by jacoballen55** [comment]
is this issue solved. I am having the same one now

**Comment by Arinze1020** [comment]
Not yet solved I had the same issues, tired but nothing. I think is the
proxy
