### ISSUE TITLE
2Captcha fails

### ISSUE THREAD

**Issue by MiracleWhip209** [hendrikbgr/YandexMail-Account-Creator#51]
Hey,

I added my API Key to the captcha_config.py, it seemed to work fine but than it didn't fill out the captcha.
The console says: https://i.imgur.com/ttjAElI.png

Can you help me pls? Sorry I've never used 2captcha before.

**Comment by hendrikbgr** [comment]
It tells you in the error code. You have to add some $ to your 2captcha account
