### ISSUE TITLE
Accounts disabled

### ISSUE THREAD

**Issue by Vjjjj007** [hendrikbgr/YandexMail-Account-Creator#52]
After the bot makes the account i want to try to open the mailbox but it says that the password is incorrect. I think the accounts get disabled right away. Is there a fix for that problem?

**Comment by Vjjjj007** [comment]
and is there a way to use proxies withour user and password, just ip addres binded proxies?

**Comment by hendrikbgr** [comment]
I am currently looking for a solution to this issue. But I have not found a bullet prove one yet. After the creation of the account did you try login in with the same proxy as you created the account with?

**Comment by Vjjjj007** [comment]
No i didnt use the same proxy but  i will try, thanks to respond

**Comment by hendrikbgr** [comment]
I seem to have the issue when the proxy is a public or shared proxy (flagged proxies). The accounts I created yesterday still seem to be working (using fresh & premium proxies)

**Comment by jacoballen55** [comment]
this is the case when a backup email is not attached. 
@hendrikbgr  can we have a function to add a recovery email?

**Comment by hendrikbgr** [comment]
@jacoballen55 should be possible. I just added a function to enable IMAP & pop3 plus creating an app password. With that, we should be able to create the first account for recovery, and then all accounts after that use that email as recovery. Do you know if the same email can be used for multiple accounts as recovery?

**Comment by jacoballen55** [comment]
that's a good idea, can use the same email for recovery, but all the accounts will get linked, and there will a possibility of detection.
it's better to have an external emails file with a recovery email and then parse the confirmation code from those emails. 
Add 1 email as recovery to 5-10 Yandex and then switch to the next email.

**Comment by jacoballen55** [comment]
> @jacoballen55 should be possible. I just added a function to enable IMAP & pop3 plus creating an app password. With that, we should be able to create the first account for recovery, and then all accounts after that use that email as recovery. Do you know if the same email can be used for multiple accounts as recovery?

Is there any doc/guide on how to use Imap?

**Comment by hendrikbgr** [comment]
@jacoballen55 If you check the current code I added a script called get_mail.py which can retrieve mails via imap. I just need to figure out the best way to link the accounts. Maybe link the created account to the previously created account

**Comment by hendrikbgr** [comment]
@jacoballen55 
![Untitled-2021-07-15-1042](https://user-images.githubusercontent.com/31375713/125759414-3ff59655-803f-431e-8a83-250e811d08b6.png)
I would this would be the best solution

**Comment by jacoballen55** [comment]
This looks good. Also, add a parameter not to link them for some people who might not want to add them

**Comment by hendrikbgr** [comment]
yes this will be an optional step

**Comment by hendrikbgr** [comment]
I would do it like this 
![Untitled-2021-07-15-1237](https://user-images.githubusercontent.com/31375713/125777492-1ad77055-b81e-4eae-b618-560581a6aa59.png)

**Comment by hendrikbgr** [comment]
I am going to add this to my list but close this issue for now (the last accounts created with IMAP enabled and app password created don't seem to get disabled)
