### ISSUE TITLE
"IndexError: list index out of range" on line 86

### ISSUE THREAD

**Issue by ThakinVunc** [hendrikbgr/YandexMail-Account-Creator#53]
Hi. I was trying to run your application and this happened:

```
Auto Account Creator Script
Getting Chrome driver...
Traceback (most recent call last):
  File "E:\New Downloads\YandexMail-Account-Creator-master\creator.py", line 86, in <module>
    version = process.communicate()[0].decode('UTF-8').strip().split()[-1]
IndexError: list index out of range

```
Can you please help out with this error? I don't exactly know how to fix it.

**Comment by hendrikbgr** [comment]
I need a bit more info.
What OS are you using?
What python version are you using?
Are you using the newest version?

**Comment by ThakinVunc** [comment]
I am using Windows 10. I am using Python 3.9.2. I'm pretty sure I am.

**Comment by hendrikbgr** [comment]
please try the latest version and see if you still get the same error.

**Comment by Sarlay** [comment]
You just have to install [google chrome](https://www.google.com/chrome/)
It is requiered as selenium useschrome to browse websites

**Comment by ThakinVunc** [comment]
Installing Chrome worked. Thanks.
