### ISSUE TITLE
Account access restricted

### ISSUE THREAD

**Issue by 9alexyt5** [hendrikbgr/YandexMail-Account-Creator#58]
I generated a bunch of accounts and when I try to log into them, they get this error:
![image](https://user-images.githubusercontent.com/55896708/129609952-0ea6a4de-e17b-4653-bb45-462ac139d315.png)
Can I somehow get rid of it in an easy way or/and prevent it from happening?

**Comment by icelts** [comment]
add your recovery email

**Comment by hendrikbgr** [comment]
Hello,
this has been an issue since more people have been using the script. I am going to add 5sim's phone verification to this script to hopefully prevent this in the future.

**Comment by hendrikbgr** [comment]
To solve this issues only access your emails via imap or smtp - not via the web gui
