### ISSUE TITLE
Captcha not going through

### ISSUE THREAD

**Issue by elijasko** [hendrikbgr/YandexMail-Account-Creator#63]
Hello, I have a issue, where the right captcha is added, but it doesnt take it and gives this error.

https://imgur.com/a/bxpCHKW

**Comment by hendrikbgr** [comment]
Hi, you have you got an account with some balance on 2captcha? And are you sure you entered the api key correctly?

**Comment by elijasko** [comment]
yes, i actually watched it fill out the captcha, but it always try to
change the first image and then solves the second image correctly but
yandex then shows that it is incorrect

ut 4. 1. 2022 o 9:25 hendrikbgr ***@***.***> napísal(a):

> Hi, you have you got an account with some balance on 2captcha? And are you
> sure you entered the api key correctly?
>

**Comment by hendrikbgr** [comment]
all issues are fixed with current version
