### ISSUE TITLE
invalid synthax

### ISSUE THREAD

**Issue by manigilar** [hendrikbgr/YandexMail-Account-Creator#64]
hello, when I paste a copy of the project, python says invalid synthax, do you have a solution? thanks in advance.

**Comment by hendrikbgr** [comment]
Hello,
could you please add a screenshot or paste the exact error you get please?

**Comment by manigilar** [comment]
![Capture pzthon](https://user-images.githubusercontent.com/97358520/149989610-1e464b97-bfd1-48f9-80b0-c89fc174f3ac.PNG)

Ask me if you need need something else, thanks for the support

**Comment by hendrikbgr** [comment]
You will need to install git for your command line first. A simple google request should give you enough instructions on how to do so.
